import type { DriverDefinition } from "./types";

export const DRIVER_DEFINITIONS: Record<string, DriverDefinition> = {
  // Revenue drivers
  orders: {
    id: "orders",
    name: "Orders",
    description: "Count of distinct orders",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["order_id"],
    calculation: "COUNT(DISTINCT order_id)",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["traffic_acquisition", "conversion_optimization", "availability_improvement"],
  },
  aov: {
    id: "aov",
    name: "Average Order Value",
    description: "Revenue per order (derived from Revenue / Orders)",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["net_revenue", "order_id"],
    calculation: "SUM(net_revenue) / COUNT(DISTINCT order_id)",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["pricing", "discount_management", "product_mix_optimization", "upselling"],
  },
  price: {
    id: "price",
    name: "Price",
    description: "Average unit price across products",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["unit_price", "net_revenue"],
    calculation: "SUM(net_revenue) / SUM(quantity)",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["pricing_strategy", "promotional_pricing", "dynamic_pricing"],
  },
  discount: {
    id: "discount",
    name: "Discount",
    description: "Average discount percentage applied",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["discount", "gross_revenue"],
    calculation: "SUM(discount) / SUM(gross_revenue) * 100",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["promotional_calendar", "discount_policy", "clearance_management"],
  },
  productMix: {
    id: "productMix",
    name: "Product Mix",
    description: "Shift in product category proportions affecting AOV",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions", "products"],
    sourceColumns: ["product_id", "net_revenue", "category"],
    calculation: "SUM(category_revenue) / SUM(total_revenue) * 100 per category",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["product_assortment", "merchandising", "new_product_launch"],
  },
  refunds: {
    id: "refunds",
    name: "Refunds",
    description: "Refund rate reducing net revenue",
    parentKPI: "revenue",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["refund", "net_revenue"],
    calculation: "SUM(refund) / SUM(gross_revenue) * 100",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["return_policy", "quality_control", "customer_service"],
  },
  availability: {
    id: "availability",
    name: "Availability",
    description: "Product availability affecting order completion",
    parentKPI: "orders",
    sourceTables: ["operations_daily"],
    sourceColumns: ["stockout_rate", "inventory_available"],
    calculation: "AVG(1 - stockout_rate) * 100",
    dimensions: ["region", "product"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["inventory_replenishment", "safety_stock", "supplier_management"],
  },
  stockouts: {
    id: "stockouts",
    name: "Stockouts",
    description: "Stockout rate causing lost orders",
    parentKPI: "orders",
    sourceTables: ["operations_daily"],
    sourceColumns: ["stockout_rate", "inventory_available"],
    calculation: "AVG(stockout_rate) * 100",
    dimensions: ["region", "product"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["inventory_replenishment", "safety_stock", "supplier_management"],
  },
  conversion: {
    id: "conversion",
    name: "Conversion Rate",
    description: "Marketing conversion rate (conversions per session)",
    parentKPI: "orders",
    sourceTables: ["marketing_daily"],
    sourceColumns: ["conversions", "sessions"],
    calculation: "SUM(conversions) / SUM(sessions) * 100",
    dimensions: ["region", "product", "channel", "campaign"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["campaign_optimization", "landing_page_optimization", "audience_targeting", "creative_testing"],
  },
  traffic: {
    id: "traffic",
    name: "Traffic",
    description: "Session volume from marketing channels",
    parentKPI: "orders",
    sourceTables: ["marketing_daily"],
    sourceColumns: ["sessions"],
    calculation: "SUM(sessions)",
    dimensions: ["region", "channel", "campaign"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["media_spend", "seo", "referral_programs", "partnerships"],
  },
  marketing: {
    id: "marketing",
    name: "Marketing",
    description: "Marketing effectiveness driving orders and conversion",
    parentKPI: "orders",
    sourceTables: ["marketing_daily"],
    sourceColumns: ["spend", "attributed_revenue", "conversions"],
    calculation: "SUM(attributed_revenue) / SUM(spend)",
    dimensions: ["region", "channel", "campaign", "product"],
    expectedDirection: "positive",
    controllable: true,
    candidateLevers: ["media_mix", "budget_allocation", "campaign_optimization", "attribution_modeling"],
  },
  stockouts_revenue: {
    id: "stockouts_revenue",
    name: "Stockouts (Revenue Impact)",
    description: "Stockouts directly reducing revenue through lost orders",
    parentKPI: "revenue",
    sourceTables: ["operations_daily", "sales_transactions"],
    sourceColumns: ["stockout_rate", "net_revenue", "inventory_available"],
    calculation: "Stockout-driven revenue loss estimation",
    dimensions: ["region", "product"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["inventory_replenishment", "safety_stock", "supplier_management"],
  },
  product_availability_aov: {
    id: "product_availability_aov",
    name: "Product Availability (AOV Impact)",
    description: "Product availability forcing substitution to lower-priced items",
    parentKPI: "aov",
    sourceTables: ["operations_daily", "sales_transactions", "products"],
    sourceColumns: ["stockout_rate", "net_revenue", "category", "base_price"],
    calculation: "Availability-driven mix shift impact on AOV",
    dimensions: ["region", "product"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["inventory_replenishment", "safety_stock", "substitution_management"],
  },
  discounting_aov: {
    id: "discounting_aov",
    name: "Discounting (AOV Impact)",
    description: "Increased discounting reducing AOV",
    parentKPI: "aov",
    sourceTables: ["sales_transactions"],
    sourceColumns: ["discount", "net_revenue", "quantity"],
    calculation: "Discount-driven AOV reduction",
    dimensions: ["region", "product", "channel"],
    expectedDirection: "negative",
    controllable: true,
    candidateLevers: ["discount_policy", "promotional_calendar", "price_elasticity_management"],
  },
};

export function getDriverDefinition(driverId: string) {
  return DRIVER_DEFINITIONS[driverId];
}

export function getDriversForKPI(kpiName: string): DriverDefinition[] {
  return Object.values(DRIVER_DEFINITIONS).filter(d => d.parentKPI === kpiName);
}

export function getAllDriverIds(): string[] {
  return Object.keys(DRIVER_DEFINITIONS);
}